<a href="https://colab.research.google.com/github/Mamtakurrey123/Pytorch-Tutorial/blob/main/global_router_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install torch torchvision torchaudio
!pip install numpy networkx matplotlib scikit-learn
!pip install torch-geometric -f https://data.pyg.org/whl/torch-2.0.0+cpu.html


   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.4/363.4 MB 4.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.8/13.8 MB 69.9 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 24.6/24.6 MB 61.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 883.7/883.7 kB 38.4 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 664.8/664.8 MB 2.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 211.5/211.5 MB 5.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 56.3/56.3 MB 14.3 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 127.9/127.9 MB 8.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 207.5/207.5 MB 5.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 21.1/21.1 MB 96.6 MB/s eta 0:00:00
  Attempting uninstall: nvidia-nvjitlink-cu12
    Found existing installation: nvidia-nvjitlink-cu12 12.5.82
    Uninstalling nvidia-nvjitlink-cu12-12.5.82:
      Successfully uninstalled nvidia-nvjitlin

# New Section

In [ ]:
!git clone https://github.com/Mamtakurrey123/Pytorch-Tutorial.git


Cloning into 'Pytorch-Tutorial'...
remote: Enumerating objects: 29, done.
remote: Counting objects: 100% (29/29), done.
remote: Compressing objects: 100% (26/26), done.
remote: Total 29 (delta 11), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (29/29), 23.87 KiB | 4.77 MiB/s, done.
Resolving deltas: 100% (11/11), done.


In [ ]:
%cd Pytorch-Tutorial
!ls


/content/Pytorch-Tutorial
GAT.ipynb	      simple_NeuralNetwork.ipynb  Tensors.ipynb
Intro_To_Colab.ipynb  tensor_ops.ipynb		  Tensot_math.ipynb


In [ ]:
!python --version


Python 3.11.12


In [ ]:
import torch
import torch_geometric
print("Torch version:", torch.__version__)
print("Torch Geometric version:", torch_geometric.__version__)


Torch version: 2.6.0+cu124
Torch Geometric version: 2.6.1


In [ ]:
!pip install networkx


In [ ]:
!mkdir -p /content/global_router_project


In [ ]:
%cd /content/global_router_project


/content/global_router_project


In [ ]:
!mkdir -p /content/ispd18_test1
!tar -xvzf /content/ispd18_test1.tgz -C /content/ispd18_test1


tar (child): /content/ispd18_test1.tgz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now


In [ ]:

!tar -xvzf /content/ispd18_test1.tgz -C /content/ispd18_test1


tar (child): /content/ispd18_test1.tgz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now


In [ ]:
!ls /content/ispd18_test1


ls: cannot access '/content/ispd18_test1': No such file or directory


In [ ]:
!mkdir -p /content/ispd18_test1
!tar -xvzf /content/ispd18_test1.tgz -C /content/ispd18_test1


tar (child): /content/ispd18_test1.tgz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now


In [ ]:
!mkdir -p /content/ispd18_test1
!tar -xvzf /content/global_router_project/ispd18_test1.tgz -C /content/ispd18_test1


ispd18_test1.input.def
ispd18_test1.input.guide
ispd18_test1.input.lef


In [ ]:
!ls /content/ispd18_test1


ispd18_test1.input.def	ispd18_test1.input.guide  ispd18_test1.input.lef


In [ ]:
!ls /content/ispd18_test1


ispd18_test1.input.def	ispd18_test1.input.guide  ispd18_test1.input.lef


In [ ]:
!pip install openpyxl
!pip install python-lefdef


ERROR: Could not find a version that satisfies the requirement python-lefdef (from versions: none)
ERROR: No matching distribution found for python-lefdef


In [ ]:
!head -n 50 /content/ispd18_test1/ispd18_test1.input.def


VERSION 5.8 ;
DIVIDERCHAR "/" ;
BUSBITCHARS "[]" ;
DESIGN ispd18_test1 ;
UNITS DISTANCE MICRONS 2000 ;

DIEAREA ( 0 0 ) ( 390800 383040 ) ;

ROW ROW_0 CoreSite 0 0 FS DO 977 BY 1 STEP 400 0
 ;
ROW ROW_1 CoreSite 0 3420 N DO 977 BY 1 STEP 400 0
 ;
ROW ROW_2 CoreSite 0 6840 FS DO 977 BY 1 STEP 400 0
 ;
ROW ROW_3 CoreSite 0 10260 N DO 977 BY 1 STEP 400 0
 ;
ROW ROW_4 CoreSite 0 13680 FS DO 977 BY 1 STEP 400 0
 ;
ROW ROW_5 CoreSite 0 17100 N DO 977 BY 1 STEP 400 0
 ;
ROW ROW_6 CoreSite 0 20520 FS DO 977 BY 1 STEP 400 0
 ;
ROW ROW_7 CoreSite 0 23940 N DO 977 BY 1 STEP 400 0
 ;
ROW ROW_8 CoreSite 0 27360 FS DO 977 BY 1 STEP 400 0
 ;
ROW ROW_9 CoreSite 0 30780 N DO 977 BY 1 STEP 400 0
 ;
ROW ROW_10 CoreSite 0 34200 FS DO 977 BY 1 STEP 400 0
 ;
ROW ROW_11 CoreSite 0 37620 N DO 977 BY 1 STEP 400 0
 ;
ROW ROW_12 CoreSite 0 41040 FS DO 977 BY 1 STEP 400 0
 ;
ROW ROW_13 CoreSite 0 44460 N DO 977 BY 1 STEP 400 0
 ;
ROW ROW_14 CoreSite 0 47880 FS DO 977 BY 1 STEP 400 0
 ;
ROW ROW_15 CoreSite 0 51300

In [18]:
from global_router_project.parse_def import parse_diearea_and_units

path = "/content/ispd18_test1/ispd18_test1.input.def"
diearea, units, w, h = parse_diearea_and_units(path)
print("DIEAREA:", diearea, "| Size (um):", w, "x", h)


DIEAREA: (0, 0, 390800, 383040)
Units per micron: 2000
Layout size in microns (W x H): 195.4 x 191.52
DIEAREA: (0, 0, 390800, 383040) | Size (um): 195.4 x 191.52


In [1]:
from global_router_project.parse_def import parse_tracks

tracks_x, tracks_y = parse_tracks(path)

print("TRACKS X lines:", tracks_x[:2])  # preview first 2
print("TRACKS Y lines:", tracks_y[:2])


DIEAREA: (0, 0, 390800, 383040)
Units per micron: 2000
Layout size in microns (W x H): 195.4 x 191.52


NameError: name 'path' is not defined

In [2]:
from global_router_project.parse_def import parse_tracks

path = "/content/ispd18_test1/ispd18_test1.input.def"
tracks_x, tracks_y = parse_tracks(path)

print("TRACKS X lines:", tracks_x[:2])
print("TRACKS Y lines:", tracks_y[:2])


TRACKS X lines: ['TRACKS X 200 DO 977 STEP 400 LAYER Metal9 ;', 'TRACKS X 200 DO 977 STEP 400 LAYER Metal8 ;']
TRACKS Y lines: ['TRACKS Y 950 DO 503 STEP 760 LAYER Metal9 ;', 'TRACKS Y 760 DO 671 STEP 570 LAYER Metal8 ;']


In [3]:
from global_router_project.parse_def import extract_track_grid

x_tracks_info = extract_track_grid(tracks_x)
y_tracks_info = extract_track_grid(tracks_y)

# Example: print grid dimensions
print("X Track Example:", x_tracks_info[0])
print("Y Track Example:", y_tracks_info[0])

# Estimate grid size
grid_cols = x_tracks_info[0]['count']
grid_rows = y_tracks_info[0]['count']
print(f"Estimated GCELL Grid: {grid_cols} columns x {grid_rows} rows")


ImportError: cannot import name 'extract_track_grid' from 'global_router_project.parse_def' (/content/global_router_project/parse_def.py)

In [4]:
!pip install matplotlib-venn

In [5]:
!apt-get -qq install -y libfluidsynth1

E: Package 'libfluidsynth1' has no installation candidate


In [6]:
# https://pypi.python.org/pypi/libarchive
!apt-get -qq install -y libarchive-dev && pip install -U libarchive
import libarchive

Selecting previously unselected package libarchive-dev:amd64.
(Reading database ... 126102 files and directories currently installed.)
Preparing to unpack .../libarchive-dev_3.6.0-1ubuntu1.4_amd64.deb ...
Unpacking libarchive-dev:amd64 (3.6.0-1ubuntu1.4) ...
Setting up libarchive-dev:amd64 (3.6.0-1ubuntu1.4) ...
Processing triggers for man-db (2.10.2-1) ...
  Preparing metadata (setup.py) ... done
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 154.7/154.7 kB 4.3 MB/s eta 0:00:00
  Created wheel for libarchive: filename=libarchive-0.4.7-py3-none-any.whl size=31629 sha256=6354e2a218a75a3589ab9eb0ebf1b8cd0b3a0a53cbfb01ee5ccd5e148cca552a
  Stored in directory: /root/.cache/pip/wheels/32/98/bd/4893d6923dd027f455b250367d402bfd69a6f4416581df46db
Successfully built libarchive


In [7]:
# https://pypi.python.org/pypi/pydot
!apt-get -qq install -y graphviz && pip install pydot
import pydot

In [8]:
!pip install cartopy
import cartopy

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.7/11.7 MB 106.8 MB/s eta 0:00:00


In [9]:
from global_router_project.parse_def import extract_track_grid

x_tracks_info = extract_track_grid(tracks_x)
y_tracks_info = extract_track_grid(tracks_y)

# Example: print grid dimensions
print("X Track Example:", x_tracks_info[0])
print("Y Track Example:", y_tracks_info[0])

# Estimate grid size
grid_cols = x_tracks_info[0]['count']
grid_rows = y_tracks_info[0]['count']
print(f"Estimated GCELL Grid: {grid_cols} columns x {grid_rows} rows")


ImportError: cannot import name 'extract_track_grid' from 'global_router_project.parse_def' (/content/global_router_project/parse_def.py)

In [10]:
!cat /content/global_router_project/parse_def.py

import re

def parse_diearea_and_units(def_path):
    diearea = (0, 0, 0, 0)
    units_per_micron = 1

    with open(def_path, 'r') as f:
        for line in f:
            if 'UNITS DISTANCE MICRONS' in line:
                units_per_micron = int(line.strip().split()[-2])
            elif 'DIEAREA' in line:
                parts = re.findall(r'\d+', line)
                diearea = tuple(map(int, parts))
                break  # Found it!

    # Calculate layout size in microns
    width = (diearea[2] - diearea[0]) / units_per_micron
    height = (diearea[3] - diearea[1]) / units_per_micron

    return diearea, units_per_micron, width, height

# Example usage
def_path = "/content/ispd18_test1/ispd18_test1.input.def"
diearea, units_per_micron, width, height = parse_diearea_and_units(def_path)

print("DIEAREA:", diearea)
print("Units per micron:", units_per_micron)
print("Layout size in microns (W x H):", width, "x", height)



In [12]:
from global_router_project.parse_def import parse_diearea_and_units, parse_tracks, extract_track_grid


ImportError: cannot import name 'extract_track_grid' from 'global_router_project.parse_def' (/content/global_router_project/parse_def.py)

In [13]:
%cd /content/Pytorch-Tutorial/global_router_project

[Errno 2] No such file or directory: '/content/Pytorch-Tutorial/global_router_project'
/content


In [14]:
!cp parse_def.py /content/global_router_project/

cp: cannot stat 'parse_def.py': No such file or directory


In [15]:
from global_router_project.parse_def import parse_diearea_and_units

path = "/content/ispd18_test1/ispd18_test1.input.def"
diearea, units, w, h = parse_diearea_and_units(path)
print("DIEAREA:", diearea, "| Size (um):", w, "x", h)


DIEAREA: (0, 0, 390800, 383040) | Size (um): 195.4 x 191.52


In [16]:
from global_router_project.parse_def import (
    parse_diearea_and_units,
    parse_tracks,
    extract_track_grid
)

path = "/content/ispd18_test1/ispd18_test1.input.def"

# Get layout info
diearea, units, w, h = parse_diearea_and_units(path)
print("Layout:", diearea, "| Microns:", w, "x", h)

# Get track lines and extract info
tracks_x, tracks_y = parse_tracks(path)
x_info = extract_track_grid(tracks_x)
y_info = extract_track_grid(tracks_y)

print("Grid columns (X):", x_info[0]['count'])
print("Grid rows    (Y):", y_info[0]['count'])


ImportError: cannot import name 'extract_track_grid' from 'global_router_project.parse_def' (/content/global_router_project/parse_def.py)

In [17]:
%cd /content/Pytorch-Tutorial/

/content/Pytorch-Tutorial


In [18]:
# Now perform the import and subsequent steps
from global_router_project.parse_def import (
    parse_diearea_and_units,
    parse_tracks,
    extract_track_grid
)

path = "/content/ispd18_test1/ispd18_test1.input.def"

# Get layout info
diearea, units, w, h = parse_diearea_and_units(path)
print("Layout:", diearea, "| Microns:", w, "x", h)

# Get track lines and extract info
tracks_x, tracks_y = parse_tracks(path)
x_info = extract_track_grid(tracks_x)
y_info = extract_track_grid(tracks_y)

print("Grid columns (X):", x_info[0]['count'])
print("Grid rows    (Y):", y_info[0]['count'])

ImportError: cannot import name 'extract_track_grid' from 'global_router_project.parse_def' (/content/global_router_project/parse_def.py)

In [19]:
%cd /content/Pytorch-Tutorial/global_router_project

[Errno 2] No such file or directory: '/content/Pytorch-Tutorial/global_router_project'
/content/Pytorch-Tutorial


In [23]:
import sys
sys.path.append('/content/global_router_project')  # ✅ Add correct path

from parse_def import (
    parse_diearea_and_units,
    parse_tracks,
    extract_track_grid
)


In [24]:
# Set DEF file path
def_path = "/content/ispd18_test1/ispd18_test1.input.def"

# Parse DIEAREA and grid size
diearea, units_per_micron, width, height = parse_diearea_and_units(def_path)
print("DIEAREA:", diearea)
print("Micron size:", width, "x", height)

# Parse TRACKS
tracks_x, tracks_y = parse_tracks(def_path)
x_info = extract_track_grid(tracks_x)
y_info = extract_track_grid(tracks_y)

# Preview grid config
print("X Tracks:", x_info[0])
print("Y Tracks:", y_info[0])

# Estimate GCELL grid
cols = x_info[0]['count']
rows = y_info[0]['count']
print(f"Estimated GCELL Grid: {cols} cols x {rows} rows")


DIEAREA: (0, 0, 390800, 383040)
Micron size: 195.4 x 191.52
X Tracks: {'direction': 'X', 'start': 200, 'count': 977, 'step': 400, 'layer': 'Metal9'}
Y Tracks: {'direction': 'Y', 'start': 950, 'count': 503, 'step': 760, 'layer': 'Metal9'}
Estimated GCELL Grid: 977 cols x 503 rows


In [25]:
import numpy as np

# Create 2D capacity matrix
gcell_capacity = np.zeros((rows, cols), dtype=int)

# Optional: count number of layers in X and Y
num_x_layers = len(x_info)
num_y_layers = len(y_info)

# Assign default capacity (number of track layers per direction)
default_capacity = num_x_layers + num_y_layers

# Fill the matrix
gcell_capacity[:, :] = default_capacity

print(f"GCELL capacity matrix shape: {gcell_capacity.shape}")
print("Sample (center 5x5 region):")
print(gcell_capacity[rows//2-2:rows//2+3, cols//2-2:cols//2+3])


GCELL capacity matrix shape: (503, 977)
Sample (center 5x5 region):
[[18 18 18 18 18]
 [18 18 18 18 18]
 [18 18 18 18 18]
 [18 18 18 18 18]
 [18 18 18 18 18]]
