<a href="https://colab.research.google.com/github/Mamtakurrey123/Pytorch-Tutorial/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import numpy as np

In [2]:
my_list = [1,2,3,4,5]
my_list


[1, 2, 3, 4, 5]

In [3]:
np1 = np.random.rand(3,4)
np1

array([[0.1048657 , 0.40556126, 0.42328655, 0.25887171],
       [0.08325754, 0.89145662, 0.51696036, 0.31133061],
       [0.425247  , 0.12417154, 0.9866779 , 0.81800709]])

In [4]:
np1.dtype

dtype('float64')

In [8]:
tensor_2d = torch.randn(3,4)
tensor_2d
tensor_2d.dtype

torch.float32

In [9]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [10]:
## Create tensor out of numpy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.1049, 0.4056, 0.4233, 0.2589],
        [0.0833, 0.8915, 0.5170, 0.3113],
        [0.4252, 0.1242, 0.9867, 0.8180]], dtype=torch.float64)