<a href="https://colab.research.google.com/github/Mamtakurrey123/Pytorch-Tutorial/blob/main/Tensot_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [9]:
import torch
import numpy as np

In [10]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [11]:
# Addition
tensor_a + tensor_b


tensor([ 6,  8, 10, 12])

In [12]:
# Addition Longhand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [13]:
# Subtraction
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [14]:
# Sub Function
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [15]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [17]:
# Mul Longhand
torch.mul(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [19]:
# Division
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [20]:
# Div Longhand
torch.div(tensor_b , tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [21]:
# Remainder Modules
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [22]:
# Remainder Longhand
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [23]:
# Exponents / Power
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])